name: Dolphin-libretro Windows x86_64

on:
  push:
    branches:
      - master
  watch: # this is a hack that lets repo owners trigger a build by starring
    types: [started]
    if: github.actor == github.event.repository.owner.login

jobs:
  Windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
    - name: Get latest CMake
      uses: lukka/get-cmake@latest
    - name: Checkout source
      run: git clone https://github.com/libretro/dolphin.git && cd dolphin && git submodule update --init
    - name: Build libretro dolphin core
      working-directory: dolphin
      run: mkdir build && cd build && cmake.exe -DLIBRETRO=ON -DENABLE_QT=0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON ..

    - name: Build the thing
      working-directory: dolphin/build
      run: cmake.exe --build . --target dolphin_libretro --config Release

    - name: Prep for release
      working-directory: dolphin/Binary
      run: Compress-Archive -CompressionLevel Optimal -Path dolphin_libretro.dll -DestinationPath ..\..\dolphin_libretro.dll.zip
    - name: Create new release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: Windows_64-bit
        prerelease: false
        title: Windows x86_64
        files: dolphin_libretro.dll.zip
    - name: Save artifact
      uses: actions/upload-artifact@v2
      with:
        name: dolphin_libretro.dll.zip
        path: dolphin_libretro.dll.zip
