name: Citra libretro Windows x86_64

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  watch: # this is a hack that lets repo owners trigger a build by starring
    types: [started]
    if: github.actor == github.event.repository.owner.login

jobs:
  Windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          wget
          git
          make
          mingw-w64-x86_64-binutils
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-zlib
          mingw-w64-x86_64-pkg-config
          zip
    - name: Get latest cmake
      uses: lukka/get-cmake@latest
    - name: Checkout source
      run: git clone https://github.com/libretro/citra.git && cd citra && git submodule update --init --recursive
    - shell: msys2 {0}
      working-directory: citra
      run: mkdir build && cd build && cmake -DENABLE_LIBRETRO=1 -DLIBRETRO_STATIC=1 -DENABLE_SDL2=0 -DENABLE_QT=0 -DCMAKE_BUILD_TYPE="Release" -DENABLE_WEB_SERVICE=0 ..
    - name: Build the thing
      working-directory: citra/build
      run: cmake --build . --target citra_libretro
    - name: Prep for release
      working-directory: citra\build\src\citra_libretro
      run: zip -9 ..\..\..\..\citra_libretro.dll.zip citra_libretro.dll
    - name: Create new release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: Windows_64-bit
        file: citra_libretro.dll.zip
        overwrite: true
